### ISSUE TITLE
Clarify whether MP Config is applied statically or dynamically 

### ISSUE THREAD

**Issue by nmittles** [eclipse/microprofile-concurrency#106]
Currently the MicroProfile Concurrency spec doesn't specify whether ManagedExecutor and ThreadContext instances created by the container support dynamic MicroProfile Config property updates.

I'd like to propose that the spec is updated to clarify that these container managed instances have MP Config properties applied statically, and do not respond to dynamic property updates. I believe there is little to be gained in the required overhead to support such dynamic updates.

Here is a suggested statement we could add:
"For ManagedExecutor and ThreadContext instances produced by the container, MicroProfie Config is applied statically. These instances will not dynamically respond to MicroProfile Config changes made after they are produced."

**Comment by njr-11** [comment]
That looks good to me.

**Comment by manovotn** [comment]
Good catch, +1 for static approach.
