### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by FroMage** [eclipse/microprofile-concurrency#11]
Unless it's already been set-up, can we add CI with snapshot deploiyments to Sonatype OSS please?

It would greatly simplify implementing it.

**Comment by njr-11** [comment]
Agree, we need to do this

**Comment by FroMage** [comment]
Looks like we have CI at https://ci.eclipse.org/microprofile/view/Concurrency/ with built modules ending up at this repo: https://repo.eclipse.org/content/repositories/microprofile-snapshots
So it looks like this should be enough.

**Comment by cescoffier** [comment]
@FroMage Did you check the PR builds?

**Comment by FroMage** [comment]
No, not yet. But I'm not sure I can trigger them.

**Comment by FroMage** [comment]
Doesn't look like I'm allowed to trigger them.
