### ISSUE TITLE
Support "Checked Transaction" behaviour

### ISSUE THREAD

**Issue by mmusgrov** [eclipse/microprofile-concurrency#116]
If there is an active transaction on multiple asynchronous completion stages then it is desirable that we avoid the situation where one thread ends a transaction whilst other threads are still using it (otherwise the work done by the other threads will not be transactional). I think it would help developers write more robust code if we provide a mechanism for the application to deal with the circumstance by allowing the creator to to provide a "Checked Transaction" handler with each managed execution similar to

```java
     public void check(boolean isCommit, Uid txId, List<Long> activeThreads);
```
which is called if a transaction is ended whilst other threads are still using it. The application would then be able to ensure that the business logic being run by threads in the activeThreads list safely terminates.

**Comment by njr-11** [comment]
It seems to me like the most natural way for applications to coordinate asynchronous transaction logic in this programming model would be to use the CompletionStage API itself. For example, using a JTA transaction (oversimplified in that try/catch blocks are omitted),

```
tx.begin()
stage1 = executor.runAsync(action1);
stage2 = executor.runAsync(action2);
stage3 = stage1.runAfterBoth(stage2, () -> tx.commit())
               .exceptionally(failure -> tx.rollback());
```

However, having written this, what concerns me here is that the main thread still has a transaction hanging around.  I think if this pattern is going to naturally fit with completion stages, we would need some sort of suspend operation from the transaction in order for the user to take it off of the main thread so that they can proceed to do other work while the transaction continues asynchronously.

**Comment by FroMage** [comment]
Also note that async actions are likely to not have thread IDs at all, since they're more often tasks that have no specific thread.

**Comment by mmusgrov** [comment]
So I think we just need to document the recommended best practice:
- for running transaction code in async stages,
- that the main thread should suspend the transaction, and
- that transaction termination should run in an after stage?

**Comment by njr-11** [comment]
Yes, documentation of this as the best practice, and probably including a simple example, should be all we need.

**Comment by mmusgrov** [comment]
Okay, I will do that and propose it here, thanks.

**Comment by FroMage** [comment]
So here's an example of how containers have to be adapted to support async propagation:

```java
HttpServletRequest req = ...;
try {
    requestContext.activate();
    return action.call(exchange, context);
} finally {
    if(req.isAsyncStarted()) {
        requestContext.deactivate();
        req.getAsyncContext().addListener(new AsyncListener() {
            @Override
            public void onComplete(AsyncEvent event) throws IOException {
                requestContext.terminate();
            }

            @Override
            public void onTimeout(AsyncEvent event) throws IOException {
                onComplete(event);
            }

            @Override
            public void onError(AsyncEvent event) throws IOException {
                onComplete(event);
            }

            @Override
            public void onStartAsync(AsyncEvent event) throws IOException {

            }
        });
    } else {
        requestContext.terminate();
    }
}
```

Or a slightly different example:

```java
@Override
public void aroundRequest(HttpRequest req, RunnableWithException<IOException> continuation) throws IOException {
        BoundRequestContext cdiContext = CDI.current().select(BoundRequestContext.class).get();
        Map<String,Object> contextMap = new HashMap<String,Object>();
        cdiContext.associate(contextMap);
        cdiContext.activate();
        try {
        	continuation.run();
        }finally {
    		if(req.getAsyncContext().isSuspended()) {
    			req.getAsyncContext().getAsyncResponse().register((CompletionCallback)(t) -> {
        			cdiContext.invalidate();
        			cdiContext.deactivate();
        			cdiContext.dissociate(contextMap);
    			});
    		}else {
    			cdiContext.invalidate();
    			cdiContext.deactivate();
    			cdiContext.dissociate(contextMap);
    		}		
        }
}
```

**Comment by njr-11** [comment]
@mmusgrov let me know if you need any help with this, or help in figuring out where to put it in the spec doc.  If you haven't found a place already, I think a very natural fit for this would be to document the best practice on the examples page, 
https://github.com/eclipse/microprofile-concurrency/blob/master/spec/src/main/asciidoc/examples.asciidoc
probably right after the example of `unchanged(ThreadContext.TRANSACTION)`.

**Comment by njr-11** [comment]
Closing this as discussed under 140.
