### ISSUE TITLE
Tests for transaction propagation to dependent stages

### ISSUE THREAD

**Issue by mmusgrov** [eclipse/microprofile-concurrency#130]
Add tests to validate that a transaction context is propagated to dependent stages when propagated(ThreadContext.TRANSACTION) is called on a ManagedExecutor.

The tests should include testing that Transaction Scoped beans are propagated to dependent stages.

I would like to provide 4 tests:

* testBasic: manually start a transaction and then run single asynchronous stage and verify that a transaction scoped bean is updated correctly and then finish the transaction
* testAsyncTransaction: same as testBasic but using @Transactional for transaction demarcation 
* testTransactionPropagation: run asynchronous stages, one after the other, where each stage tests one of the Transactional.TxType element attributes (MANDATORY, NEVER, NOT_SUPPORTED, REQUIRED, REQUIRES_NEW, SUPPORTS). Validate that a transaction scoped bean is updated in accordance with the semantics of this element.
* testConcurrentTransactionPropagation: start two concurrent asynchronous stages and verify that a transaction scoped bean is updated twice

**Comment by njr-11** [comment]
+1 to these test scenarios.

A good place for these would be https://github.com/eclipse/microprofile-concurrency/blob/master/tck/src/main/java/org/eclipse/microprofile/concurrency/tck/cdi/BasicCDITest.java given that they require CDI.

To allow for implementations that don't support this optional feature of the spec, the TCK tests should all follow the precedent of [ManagedExecutorTest.propagateTransactionContextJTA](https://github.com/eclipse/microprofile-concurrency/blob/master/tck/src/main/java/org/eclipse/microprofile/concurrency/tck/ManagedExecutorTest.java) in trapping for the following exceptions indicating lack of support and considering either these a passing result:

- IllegalStateException on builder.propagated(ThreadContext.TRANSACTION).build (indicates propagate isn't supported at all, even propagating the absence of a transaction)
- UnsupportedOperationException on any operation that causes context capture within a transaction

Regarding testConcurrentTransactionPropagation, we don't yet have a precedent for how to signal lack of support for propagation to multiple threads in parallel, but I think it would make sense to fail the second completion stage with IllegalStateException indicating that the transaction is already active on another thread.

Let me know if you need help with any of these.  I'd be happy to assist.
