### ISSUE TITLE
Is there a better way to configure which thread context types?

### ISSUE THREAD

**Issue by njr-11** [eclipse/microprofile-concurrency#19]
This is opened to cover a comment that @Emily-Jiang made on general mechanism for identify thread context types on the builders/config.  See https://github.com/eclipse/microprofile-concurrency/pull/8

Specifically, it applies in the following places:

ManagedExecutorBuilder:
`propagated(String... types);`

ThreadContextBuilder:
`propagated(String... types);`
`unchanged(String... types);`

ManagedExecutorConfig:
`String[] propagated() default { ThreadContext.APPLICATION, ThreadContext.CDI, ThreadContext.SECURITY };`

ThreadContextConfig:
`String[] value() default { ThreadContext.APPLICATION, ThreadContext.CDI, ThreadContext.SECURITY };`
`String[] unchanged() default {};`

Emily's comment was,
_This is [not] type safe though. Is it possible to pass in ThreadContext type instead and then in ThreadContext to create instances for the contexts_

While it doesn't make sense to supply ThreadContext type (because that implies configuration of `unchanged` contexts which would be wrong for ManagedExecutors), it should be considered whether the configuration of context types can be improved in other ways.  The main problem with using an enumerated type is that we need thread context providers to be able to define their own types.

**Comment by njr-11** [comment]
One possibility:
`Class<? extends ThreadContextType>[] propagated() default { ApplicationContext.class, CDIContext.class, SecurityContext.class };`
and the corresponding
`executor = builder.propagated(ApplicationContext.class, CDIContext.class, SecurityContext.class).build()`

This would require the thread context provider to supply an additional class - one that implements ThreadContextType - instead of supplying a String constant.  It would virtually eliminate the possibility of multiple thread context providers providing the same type because the type would be qualified with the package name.  But I'm not so sure I like the idea.  I wanted to document it though to see what others think of it, or in case it leads to any better proposals.

**Comment by FroMage** [comment]
Another possibility is to have:

```java
ThreadContextType[] propagated() default { InitialContextType.APPLICATION, InitialContextType.CDI, InitialContextType.SECURITY };

interface ThreadContextType{}
enum InitialContextType implements ThreadContextType {
 APPLICATION, CDI, SECURITY;
}
```

IIRC something like that is done in JAXRS for HTTP methods, to keep it extensible.

**Comment by njr-11** [comment]
@FroMage I like that approach with the enum extending the interface, but unfortunately Java doesn't allow annotations with types other than primitive, String, Class, enum, annotation or arrays of these, so it won't compile.

**Comment by FroMage** [comment]
Ah, right, sorry.

**Comment by njr-11** [comment]
Focusing on the two options so far from the user's perspective,

Usage of existing pattern:
```
@Inject @ManagedExecutorConfig(propagated = { ThreadContext.APPLICATION, ThreadContext.CDI, ThreadContext.SECURITY })
ManagedExecutor executor;
```
With the above pattern, the user is encouraged to use the constants for compile safety, but they are not forced to.  This can be an advantage when multiple third party providers introduce custom contexts.  For example if two different providers want to provide a "ABC" context, the application can just specify "ABC" rather than having to choose between org.firstprovider.context.ABCContext vs com.secondprovider.contexttypes.ABCContext.  The same is true when providers declare prerequisites.

Usage of alternate pattern based on classes:
```
@Inject @ManagedExecutorConfig(propagated = { ApplicationContext.class, CDIContext.class, SecurityContext.class })
ManagedExecutor executor;
```
With this second pattern, typos made by the user will not get past compile time (unless their typo ended up being a different type that is actually valid).  But it also forces the user to hard code vendor-specific classes in the case of third-party defined custom context types.

**Comment by njr-11** [comment]
The limitations of the alternate pattern (described in previous comment) are too severe and no viable alternatives have been suggested in the month or so that this has remained open, so we will stick with the existing pattern.  If anyone does come up with other ideas at a future point, please feel free to reopen this issue.
