### ISSUE TITLE
ManagedExecutor.newIncompleteFuture

### ISSUE THREAD

**Issue by njr-11** [eclipse/microprofile-concurrency#21]
One thing that we are missing on ManagedExecutor is an equivalent for the ability to construct a new instance of CompletableFuture which is not completed and chain dependent stages, later completing the original CompletableFuture.  A workaround for this is requesting an already-completed completable future, 
`managedExecutor.completedFuture(unusedResultOfCorrectType).newIncompleteFuture();`
However, this pattern seems like it could be common enough that a convenience method would be valuable,
`CompletableFuture<Integer> cf = managedExecutor.newIncompleteFuture(Integer.class)`

**Comment by FroMage** [comment]
Any reason why `<T> CompletableFuture<T> newIncompleteFuture(Class<T>)` rather than `<T> CompletableFuture<T> newIncompleteFuture()`?

**Comment by njr-11** [comment]
@FroMage no good reason that I know of. What you suggested is better, so let's use that instead.
