### ISSUE TITLE
Register ConcurrencyProvider via ServiceLoader

### ISSUE THREAD

**Issue by FroMage** [eclipse/microprofile-concurrency#26]
I believe other MP specs are doing it this way (MP-Config for example), rather than via the API, and it's probably a good idea to copy that set-up. It makes integration easier for users who only have to add the implementation to the classpath, and we can always keep the API for manual registration too.

**Comment by njr-11** [comment]
I thought about using ServiceLoader to have the container register ConcurrencyProvider, but at the time was concerned about the possibility that applications or other JARs might try to supply their own ConcurrencyProvider which could partially supplant the container's.  To eliminate that possibility, I wrote in the ConcurrencyProvider.register SPI with semantics that enforce a single ConcurrencyProvider for the whole system.  While this doesn't completely prevent an unexpected provider from being registered first, it does give the container the opportunity to at least fail and refuse to continue if ever prevented from supplying the ConcurrencyProvider for the system.  A solution that relied solely upon ServiceLoader would allow for either implementation being chosen.

That said, I can also see the convenience of being able to supply the implementation via ServiceLoader, and  the two approaches could certainly be made to work in combination (if instance not provided by register method, then use the ServiceLoader).  It looks like MP Config, which you mentioned, similarly allows for two ways to register its ConfigProviderResolver: ServiceLoader and setInstance, so we would be consistent with that, along with some better protection around restricting the ability to clear the provider.

**Comment by njr-11** [comment]
I just noticed that pull #25 already includes the exact changes needed, so I switched the owner to @FroMage who created that pull, and I'll add a fixes comment to #25 for this issue to ensure this gets closed out when that delivers.

**Comment by FroMage** [comment]
Yeah, except that PR was not meant to deliver this change, I wanted to discuss it first, and it would need to be documented. The PR was mostly meant to start discussing the TCK :)

**Comment by FroMage** [comment]
#29 has the proper docs. If it's OK by you we can merge it.

**Comment by njr-11** [comment]
Reviewed #29 and the changes looked good, so I have merged it.
