### ISSUE TITLE
Identically named withCurrentContext methods cause compile errors with lambdas

### ISSUE THREAD

**Issue by njr-11** [eclipse/microprofile-concurrency#32]
ThreadContext has many methods named `withCurrentContext` for contextualizing completion stage actions.  Completion stage actions are very often lambdas.  Some of these actions are functional interfaces with the same parameters or return types.  When written as lambdas, it becomes unclear which method is being invoked.  For example contextualizing a Callable and a Supplier would be done the same way,

```
    Callable<Long> callable = threadCtx.withCurrentContext(() -> {
        return 10l;
    });

    Supplier<Long> supplier = threadCtx.withCurrentContext(() -> {
        return 10l;
    });
```
This fails to compile due to the ambiguity:

```
  error: reference to withCurrentContext is ambiguous
        Callable<Long> callable = threadCtx.withCurrentContext(() -> {
                                           ^
  both method <R#1>withCurrentContext(Callable<R#1>) in ThreadContext and method <R#2>withCurrentContext(Supplier<R#2>) in ThreadContext match
  where R#1,R#2 are type-variables:
    R#1 extends Object declared in method <R#1>withCurrentContext(Callable<R#1>)
    R#2 extends Object declared in method <R#2>withCurrentContext(Supplier<R#2>)
```

It should be noted that this can be worked around by casting the lambda,
```
    Callable<Long> callable = threadCtx.withCurrentContext((Callable<Long>) () -> {
        return 10l;
    });
```
but that provides a poor user experience.

We should simply rename withCurrentContext to be different for each type of action/signature.

I'll suggest either of the following sets of names:

Option A:
.contextualCallable
.contextualSupplier
.contextualRunnable
.contextualFunction
.contextualConsumer

Option B:
.currentContextCallable
.currentContextSupplier
.currentContextRunnable
.currentContextFunction
.currentContextConsumer

I'm leaning toward option A, which is shorter.  Also, option B might be confusing in a few of the cases.

**Comment by FroMage** [comment]
The first option seems better to me if only because it's shorter.
