### ISSUE TITLE
concurrency: support per-application SPI providers

### ISSUE THREAD

**Issue by FroMage** [eclipse/microprofile-concurrency#5]
In order for mp-concurrency to replace [Reactive Contexts](https://reactiverse.io/reactive-contexts/) which is currently used by RESTEasy to provide context propagation, further to #16 we need to be able to declare providers per application, and not just globally.

When integrating Reactive Contexts in RESTEasy we noticed that in WildFly we had issues because it uses a modular class loader (JBoss Modules) and supports multiple independent deployments of applications.

In this particular case the WildFly distrib was loaded with RESTEasy and Reactive Contexts, and then we had two independent user applications (two `.war` files) that each had their own sets of context providers.

Having a global list of context providers held as a static variable did not work: we needed to have a per-deployment list of context providers.

On deployment, RESTEasy instantiates a new Reactive Contexts subsystem, and stores it in a thread-local (the assumption being that every RESTEasy deployment is tied initially to a separate thread). From there, every thread which serves RESTEasy request has that thread-local propagated and it is used to look up the set of context providers that participate in context propagation.

Copied from https://github.com/eclipse/microprofile-sandbox/issues/17

**Comment by njr-11** [comment]
Could this be addressed by documenting a requirement that ContextProviders are loaded using the classloader that is present on the thread at the point of injection (if CDI is used) or the point of construction (if builder approach is used) of the ThreadContext/ManagedExecutor instance ?

**Comment by FroMage** [comment]
Well, it also depends how the ThreadContext is initialised. For ReactiveContexts in RESTEasy it's initialised at startup, and kept in RESTEasy's context (the irony). For each request it will then be set to the current thread's ReactiveContext, so that context capturing works.

The big problem was that we need context propagation for RxJava, which only supports a single hook, defined in a static. That hook (context propagator) needs to obtain the current context to capture/restore it. I don't think it can use injection, and it can't build a new context, so it has to look it up for the current request, which is why a thread-local works. After that it will let the context handle capturing/propagation so we don't need the thread-local anymore. But it's the initial lookup that has to be per-request. I suppose it could be per-ClassLoader, but still that association has to be kept somewhere so RxJava's context propagator can find it.

**Comment by FroMage** [comment]
I believe #30 solves this issue.

**Comment by njr-11** [comment]
Can this be closed out with delivery of pull #30 ?

**Comment by FroMage** [comment]
Yes
