### ISSUE TITLE
Should NamedInstance qualifier's value be Nonbinding?

### ISSUE THREAD

**Issue by njr-11** [eclipse/microprofile-concurrency#52]
This issue is opened to answer the question raised in issue #46 around whether the value of the NamedInstance qualifier should be Nonbinding or not.

**Comment by aguibert** [comment]
Re-posting my reasoning from issue #46 as to why NamedInstance should be a binding qualifier attribute:

---

If we were to make NamedExecutor.value() non-binding, that would limit the qualifier to only being useful in conjunction with @ManagedExecutorConfig. If we do go with non-binding, then the standard producer approach will not work with the the spec-provided @NamedExecutor qualifier:

```java
// This would give a deployment error if we make NamedExecutor.value() non-binding
@Produces @NamedExecutor("A") @ApplicationScoped
ManagedExecutor exec = // init...

@Inject @NamedExecutor("A)
ManagedExecutor exec;
```

Although I agree that the implementation may be a bit simpler if we go with non-binding, it doesn't seem worth the tradeoff of causing the above scenario to not work.

**Comment by njr-11** [comment]
This issue is no longer valid because NamedInstance was removed from the spec and thus the issue no longer applies.
