### ISSUE TITLE
Introduce annotation literals for easy inline creation of annotations

### ISSUE THREAD

**Issue by manovotn** [eclipse/microprofile-concurrency#55]
I think we should introduce helper classes for users and integrators to be able to instantiate an annotation with given parameters programatically.

This is quite common in CDI, see for instance [`NamedLiteral` qualifier](https://github.com/cdi-spec/cdi/blob/master/api/src/main/java/javax/enterprise/inject/literal/NamedLiteral.java) (placed in separate class only because CDI doesn't "own" Named class, that javax.annotation)
or the [`@ApplicationScoped`](https://github.com/cdi-spec/cdi/blob/master/api/src/main/java/javax/enterprise/context/ApplicationScoped.java#L96) annotation which is not a qualifier. And many more...

CDI also offers a util class to easily implement this - [`AnnotationLiteral`](https://github.com/cdi-spec/cdi/blob/master/api/src/main/java/javax/enterprise/util/AnnotationLiteral.java).

I think we could easily leverage that and have a nice QoL improvement.
For instance user wanting to get hold of a named ME instance via `Instance` object in CDI could then do `Instance<Object>.select(ManagedExecutor.class, NamedInstance.NamedInstanceLiteral.of("myExec"))` as opposed creating another anonymous class to be able to reference the qualifier from code.

Will send PR shortly.

**Comment by aguibert** [comment]
+1, I had just made a helper method for this in OpenLiberty but having a spec-provided literal creator method will be nice

**Comment by aguibert** [comment]
to be consistent with other CDI literals, I think the name should just be `NamedInstance.Literal.of("myExec")`.  For example, all the qualifier annotations in `javax.enterprise.inject` follow the pattern of `<CLASS>.Literal.INSTANCE`

**Comment by manovotn** [comment]
Not all of them, it varies based on whether the spec owns the annotation or not.
And ultimately it is a matter of choice, I am fine swapping it to just `Literal`.
