### ISSUE TITLE
ThreadContext.Builder and ManagedExecutor.Builder doc unclear on context set overlap

### ISSUE THREAD

**Issue by nmittles** [eclipse/microprofile-concurrency#64]
The JavaDoc for ThreadContext.Builder and ManagedExecutorBuilder are either incomplete or missing for defining behaviour related to overlap regarding the "cleared", "propagated", and "unchanged" thread context sets.

The JavaDoc should explicitly state that defining the same thread context type in more than one of "cleared", "propagated", or "unchanged" categories results in an error.

**Comment by njr-11** [comment]
Thanks for catching this bug.  The equivalent CDI annotation classes ThreadContextConfig and ManagedExecutorConfig state this requirement, but it is missing from the builders.
