### ISSUE TITLE
Update spec language around cleared default value.

### ISSUE THREAD

**Issue by FroMage** [eclipse/microprofile-concurrency#80]
#74, #75 and #77 made apparent the fact that the documentation of `cleared` is sort-of lying when it declares its default value to be `TRANSACTION` when other parts of the spec such as the doc for `propagated` then mention that in fact if `propagated` does not contain `ALL_REMAINING` the default value for `cleared` changes to `ALL_REMAINING`.

I don't disagree with the usefulness of having everything cleared by default when you specify specific contexts to be propagated, but then the docs of `cleared` should mention that its default value can changed based on the value of `propagated`

**Comment by njr-11** [comment]
Agree.  I think we should add clarifying language like this to the definition of `cleared`, because this is where the user will be looking for what to expect for cleared context:

> `{@link ThreadContext#ALL_REMAINING}` is automatically appended to the set of `cleared` context if neither the `propagated` set nor the `unchanged` set include `{@link ThreadContext#ALL_REMAINING}`.

**Comment by FroMage** [comment]
That'd be perfect.
