### ISSUE TITLE
Define/document the error path behavior when MPConfig incorrectly specified for override

### ISSUE THREAD

**Issue by njr-11** [eclipse/microprofile-concurrency#86]
It was discussed on a prior MP Concurrency call that it will be an error path for someone to attempt to override an injection point with standard qualifier(s) and no `@ManagedExecutorConfig` annotation, for example,

```
@Inject @NamedInstance("exec1") ManagedExecutor myExecutor;
```

This issue is opened to decide exactly what error path behavior the spec should define.
Once determined, update the relevant section https://github.com/eclipse/microprofile-concurrency/blob/master/spec/src/main/asciidoc/mpconfig.asciidoc with the resolution.

**Comment by nmittles** [comment]
On another MP Concurrency call this was discussed further.  We decided to check on what other MP specs are doing for this sort of error path (if anything), and potentially mimic what the other specs are doing.

I'm taking this todo to investigate what other MP specs are doing.

**Comment by nmittles** [comment]
I checked with a few of my MP contacts and browsed through the MP specs. I wasn't able to find much on error paths regarding MP Config in general. The error paths that are covered are values that are read in and cause specific configuration issues. These paths are handled the same as incorrect configuration in general, such as bad values provided for an annotation. I was not able to find any instances of specs going out of their way to find MP config values that don't map to anything, and reporting an error.

**Comment by nmittles** [comment]
Discussed on the Jan 31st 2019 call, and decided we will cancel this issue. This portion of the spec is being updated under a separate issue and will include a change that switches the wording from "It is an error to specify ..." to "It would be incorrect to specify ..."
